//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorsAdapterTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssessorsAdapterTest.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;HTML&gt;&lt;HEAD&gt;
        ///&lt;TITLE&gt;Polk/Des Moines Assessor - Query Too Vague&lt;/TITLE&gt;
        ///&lt;/HEAD&gt;
        ///&lt;BODY BGCOLOR=&quot;#FFFFEA&quot;   &gt;
        ///  &lt;CENTER&gt;
        ///  &lt;TABLE BORDER=0 CELLSPACING=&quot;0&quot;&gt;
        ///    &lt;TR&gt;
        ///    &lt;TD VALIGN=&quot;top&quot; ALIGN=&quot;CENTER&quot;&gt;
        ///         &lt;IMG SRC=&quot;/images/look/logo/small.gif&quot; VALIGN=&quot;middle&quot;&gt;
        ///      &lt;BR&gt;
        ///      &lt;FONT SIZE=&quot;-1&quot;&gt;[ &lt;A HREF=&quot;/index.html&quot;&gt;Home&lt;/A&gt; ][ &lt;A HREF=&quot;/web/inven/query/queryAll.html&quot;&gt;General Query&lt;/A&gt; ]
        ///	 [ &lt;A HREF=&quot;/web/inven/query/queryLegal.html&quot;&gt;Legal Query&lt;/A&gt; ]
        ///	 [ &lt;A HREF=&quot;/web/inven/query/queryHome.html&quot;&gt;HomeOwn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _6324_Wilcot_Ct {
            get {
                return ResourceManager.GetString("_6324_Wilcot_Ct", resourceCulture);
            }
        }
    }
}
