//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessorsAdapterTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssessorsAdapterTest.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///&lt;title&gt;Polk/Des Moines Assessor - Query Results&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#FFFFEA&quot;&gt;
        ///  &lt;center&gt;
        ///  &lt;table border=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///    &lt;tr&gt;
        ///    &lt;td valign=&quot;top&quot; align=&quot;CENTER&quot;&gt;
        ///         &lt;img src=&quot;/images/look/logo/small.gif&quot; valign=&quot;middle&quot;&gt;
        ///      &lt;br&gt;
        ///      &lt;font size=&quot;-1&quot;&gt;[ &lt;a href=&quot;/index.html&quot;&gt;Home&lt;/a&gt; ][ &lt;a href=&quot;/web/inven/query/queryAll.html&quot;&gt;General Query&lt;/a&gt; ]
        ///	 [ &lt;a href=&quot;/web/inven/query/queryLegal.html&quot;&gt;Legal Query&lt;/a&gt; ]
        ///	 [ &lt;a href=&quot;/web/inven/query/queryHome.html&quot;&gt;HomeOwner  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _123_Fake_St {
            get {
                return ResourceManager.GetString("_123_Fake_St", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///&lt;title&gt;Polk/Des Moines Assessor - 320/04116-569-000 Listing&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#FFFFEA&quot;&gt;
        ///  &lt;center&gt;
        ///  &lt;table border=&quot;0&quot; cellspacing=&quot;7&quot;&gt;
        ///    &lt;tr&gt;
        ///    &lt;td valign=&quot;top&quot; align=&quot;CENTER&quot;&gt;
        ///         &lt;img src=&quot;/images/look/logo/small.gif&quot; valign=&quot;middle&quot;&gt;
        ///      &lt;br&gt;
        ///      &lt;font size=&quot;-1&quot;&gt;[ &lt;a href=&quot;/index.html&quot;&gt;Home&lt;/a&gt; ]
        ///		  [ &lt;a href=&quot;/web/inven/query/queryAll.html&quot;&gt;General Query&lt;/a&gt; ]
        ///		  [ &lt;a href=&quot;/web/inven/query/queryLegal.html&quot;&gt;Legal Query&lt;/a&gt; ]
        ///		  [ &lt;a href=&quot;/web/inven/query/query [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _4624_Tamara_Ln {
            get {
                return ResourceManager.GetString("_4624_Tamara_Ln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///&lt;title&gt;Polk/Des Moines Assessor - 241/00523-067-914 Listing&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#FFFFEA&quot;&gt;
        ///  &lt;center&gt;
        ///  &lt;table border=&quot;0&quot; cellspacing=&quot;7&quot;&gt;
        ///    &lt;tr&gt;
        ///    &lt;td valign=&quot;top&quot; align=&quot;CENTER&quot;&gt;
        ///         &lt;img src=&quot;/images/look/logo/small.gif&quot; valign=&quot;middle&quot;&gt;
        ///      &lt;br&gt;
        ///      &lt;font size=&quot;-1&quot;&gt;[ &lt;a href=&quot;/index.html&quot;&gt;Home&lt;/a&gt; ]
        ///		  [ &lt;a href=&quot;/web/inven/query/queryAll.html&quot;&gt;General Query&lt;/a&gt; ]
        ///		  [ &lt;a href=&quot;/web/inven/query/queryLegal.html&quot;&gt;Legal Query&lt;/a&gt; ]
        ///		  [ &lt;a href=&quot;/web/inven/query/query [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _6324_Wilcot_Ct {
            get {
                return ResourceManager.GetString("_6324_Wilcot_Ct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;                                                                  
        ///&lt;head&gt;                                                                  
        ///&lt;title&gt;Polk County Treasurer&apos;s Office - Database Inquiry&lt;/title&gt;                           
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///&lt;link rel=&quot;StyleSheet&quot; href=&quot;/includes/main.css&quot; type=&quot;text/css&quot;&gt;
        ///&lt;script language=&quot;JavaScript&quot;&gt;
        ///&lt;!--
        ///
        /// var BaseUrl  = location.protocol + &apos;//&apos; + location.hostname + &apos;/&apos;;
        /// var ImageUrl = BaseUrl + &apos;ima [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _6324_Wilcot_Ct___taxes {
            get {
                return ResourceManager.GetString("_6324_Wilcot_Ct___taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///&lt;title&gt;Polk/Des Moines Assessor - 180/00847-407-000 Listing&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#FFFFEA&quot;&gt;
        ///  &lt;center&gt;
        ///  &lt;table border=&quot;0&quot; cellspacing=&quot;7&quot;&gt;
        ///    &lt;tr&gt;
        ///    &lt;td valign=&quot;top&quot; align=&quot;CENTER&quot;&gt;
        ///         &lt;img src=&quot;/images/look/logo/small.gif&quot; valign=&quot;middle&quot;&gt;
        ///      &lt;br&gt;
        ///      &lt;font size=&quot;-1&quot;&gt;[ &lt;a href=&quot;/index.html&quot;&gt;Home&lt;/a&gt; ]
        ///		  [ &lt;a href=&quot;/web/inven/query/queryAll.html&quot;&gt;General Query&lt;/a&gt; ]
        ///		  [ &lt;a href=&quot;/web/inven/query/queryLegal.html&quot;&gt;Legal Query&lt;/a&gt; ]
        ///		  [ &lt;a href=&quot;/web/inven/query/query [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _9260_NW_36th_St {
            get {
                return ResourceManager.GetString("_9260_NW_36th_St", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;                                                                  
        ///&lt;head&gt;                                                                  
        ///&lt;title&gt;Polk County Treasurer&apos;s Office - Database Inquiry&lt;/title&gt;                           
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///&lt;link rel=&quot;StyleSheet&quot; href=&quot;/includes/main.css&quot; type=&quot;text/css&quot;&gt;
        ///&lt;script language=&quot;JavaScript&quot;&gt;
        ///&lt;!--
        ///
        /// var BaseUrl  = location.protocol + &apos;//&apos; + location.hostname + &apos;/&apos;;
        /// var ImageUrl = BaseUrl + &apos;ima [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _9260_NW_36th_St___taxes {
            get {
                return ResourceManager.GetString("_9260_NW_36th_St___taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///&lt;title&gt;Polk/Des Moines Assessor - Query Results&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#FFFFEA&quot;&gt;
        ///  &lt;center&gt;
        ///  &lt;table border=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///    &lt;tr&gt;
        ///    &lt;td valign=&quot;top&quot; align=&quot;CENTER&quot;&gt;
        ///         &lt;img src=&quot;/images/look/logo/small.gif&quot; valign=&quot;middle&quot;&gt;
        ///      &lt;br&gt;
        ///      &lt;font size=&quot;-1&quot;&gt;[ &lt;a href=&quot;/index.html&quot;&gt;Home&lt;/a&gt; ][ &lt;a href=&quot;/web/inven/query/queryAll.html&quot;&gt;General Query&lt;/a&gt; ]
        ///	 [ &lt;a href=&quot;/web/inven/query/queryLegal.html&quot;&gt;Legal Query&lt;/a&gt; ]
        ///	 [ &lt;a href=&quot;/web/inven/query/queryHome.html&quot;&gt;HomeOwner  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _9823_Laguna_Dr {
            get {
                return ResourceManager.GetString("_9823_Laguna_Dr", resourceCulture);
            }
        }
    }
}
